-- DDL
create or replace TABLE SOURCEDB.PUBLIC.LND_POS_TRN_LVL_HDR (
	TERR_CD NUMBER(38,0),
	MCD_GBAL_LCAT_ID_NU NUMBER(38,0),
	POS_ORD_KEY_ID VARCHAR(50),
	POS_BUSN_DT DATE,
	POS_EVNT_TYP_ID NUMBER(38,0),
	DYPT_ID_NU NUMBER(38,0),
	CURN_ISO_NU NUMBER(38,0),
	POS_ORD_DT DATE,
	POS_DVCE_ID VARCHAR(25),
	POS_ORD_BEG_TM VARCHAR(50),
	POS_ORD_UNIQ_ID VARCHAR(50),
	POS_ORD_NU NUMBER(38,0),
	POS_HOLD_TM_SC_QT NUMBER(38,0),
	POS_TOT_TM_SC_QT NUMBER(38,0),
	HAND_HELD_ORD_FL NUMBER(38,0),
	POS_KVS_SIDE_CD VARCHAR(25),
	SRCE_CUST_OFFR_ID NUMBER(38,0),
	CUST_OFFR_OVRD_FL NUMBER(38,0),
	CUST_OFFR_APPD_FL NUMBER(38,0),
	SRCE_DIGL_OFFR_ID NUMBER(38,0),
	SRCE_INDV_ID NUMBER(38,0),
	TERR_PYMT_METH_CD NUMBER(38,0),
	TERR_PRD_DLVR_METH_CD NUMBER(38,0),
	TERR_POS_AREA_CD NUMBER(38,0),
	POS_TRN_KIND_TYP_ID NUMBER(38,0),
	POS_TOT_NET_TRN_AM NUMBER(38,2),
	POS_TOT_GRSS_TRN_AM NUMBER(38,2),
	POS_TOT_TAX_AM NUMBER(38,2),
	POS_TOT_FOOD_COST_AM NUMBER(38,4),
	POS_TOT_PAPR_COST_AM NUMBER(38,4),
	POS_TOT_OTH_COST_AM NUMBER(38,2),
	POS_TOT_COST_AM NUMBER(38,4),
	CSHL_PYMT_ATHZ_ID VARCHAR(25),
	CSHL_PYMT_ID VARCHAR(50),
	LOAD_DW_AUDT_TS VARCHAR(50),
	UPDT_DW_AUDT_TS VARCHAR(50),
	DW_FILE_ID NUMBER(38,0),
	ESTD_TRN_GEST_GRP_SIZE_NU NUMBER(38,2),
	POS_TOT_ITM_CPNT_QT NUMBER(38,0),
	SRCE_CUST_PROF_ID VARCHAR(25),
	HR_ID_NU NUMBER(38,0),
	POS_KVS_RCPT_ID NUMBER(38,0),
	DIGL_ORD_ID VARCHAR(100),
	PAID_MOBL_ORD_FL NUMBER(38,0),
	MOBL_ORD_FL NUMBER(38,0),
	DLVR_3PO_ID NUMBER(38,0),
	DLVR_3PO_BILL_SALE_FL NUMBER(38,0),
	DLVR_3PO_NA VARCHAR(100),
	DLVR_3PO_ORD_ID VARCHAR(150),
	TBLE_SERV_ID NUMBER(38,0),
	TBLE_SERV_RDCT_FL NUMBER(38,0),
	TBLE_SERV_MODE_CD VARCHAR(25),
	DLVR_CHNL_CD VARCHAR(25),
	DCS_CUST_ACCT_ID NUMBER(38,0),
	OTH_CUST_ID VARCHAR(50),
	CUST_TYPE_ID NUMBER(38,0),
	POS_TOT_PRMO_QT NUMBER(38,0),
	POS_TOT_OFFR_APPD_QT NUMBER(38,0),
	DIGL_ORD_CK_IN_CD VARCHAR(50),
	ORD_TM_SC_QT NUMBER(38,3),
	CASH_TEND_TM_SC_QT NUMBER(38,3),
	OEPE_TM_SC_QT NUMBER(38,3),
	TOT_SERV_TM_SC_QT NUMBER(38,3),
	IN_STR_R2P_TM_SC_QT NUMBER(38,3),
	DRV_PSNT_TM_SC NUMBER(38,3),
	DRV_PULL_FRWD_TM_SC_QT NUMBER(38,3),
	DRV_PULL_FRWD_FL NUMBER(38,0),
	MOBL_ORD_ATTD_FL VARCHAR(25),
	POS_SOS_TM_IVLD_FL NUMBER(38,0),
	POS_TOT_DIGL_OFFR_DISC_AM NUMBER(38,2),
	POS_TOT_TRAY_ITM_QT NUMBER(38,0),
	POS_TOT_BM_AC_QT NUMBER(38,0),
	POS_TOT_PRMO_BM_AC_QT NUMBER(38,0),
	POS_CSHL_CARD_PVDR_TYP_CD VARCHAR(50),
	POS_CSHL_CARD_SEQ_ID NUMBER(38,0),
	CRNT_OPS_TRGT_MET_FL NUMBER(38,0),
	UNTL_SRV_OUTR_FL NUMBER(38,0),
	UNTL_TOT_OUTR_FL NUMBER(38,0),
	UNTL_PAY_OUTR_FL NUMBER(38,0),
	UNTL_STR_OUTR_FL NUMBER(38,0),
	HELD_TM_OUTR_FL NUMBER(38,0),
	UNTL_STR_ABOV_UNTL_SRV_OUTR_FL NUMBER(38,0),
	UNTL_PAY_ABOV_UNTL_SRV_OUTR_FL NUMBER(38,0),
	UNTL_SRV_OVER_MAX_OUTR_FL NUMBER(38,0),
	POS_TOT_LIST_NET_TRN_AM NUMBER(38,2),
	POS_TOT_LIST_GRSS_TRN_AM NUMBER(38,4),
	POS_TOT_OTH_TAX_AM NUMBER(38,2),
	POS_TOT_BM_DISC_AM NUMBER(38,2),
	POS_TOT_NET_PRMO_DISC_AM NUMBER(38,2),
	POS_TOT_GRSS_PRMO_DISC_AM NUMBER(38,4),
	POS_TOT_PYMT_METH_QT NUMBER(38,0),
	POS_TOT_ADD_CUSM_QT NUMBER(38,0),
	POS_TOT_RMOV_CUSM_QT NUMBER(38,0),
	POS_TOT_CUSM_QT NUMBER(38,0),
	POS_PYMT_TYP_DS VARCHAR(25),
	TOT_ORD_AM_CHG_AFT_RCLL_FL NUMBER(38,0),
	ORD_ITM_CHG_AFT_RCLL_FL NUMBER(38,0),
	TOT_CUST_ID_EVNT_CNT_QT NUMBER(38,0),
	PLCD_POS_CHNL_ID NUMBER(38,0),
	PLCD_POS_CHNL_DS VARCHAR(25),
	PAID_POS_CHNL_ID NUMBER(38,0),
	PAID_POS_CHNL_DS VARCHAR(25),
	PSNT_POS_CHNL_ID NUMBER(38,0),
	PSNT_POS_CHNL_DS VARCHAR(25),
	LINK_PYMT_USED_STUS_CD VARCHAR(25),
	POS_SALE_STRT_TS VARCHAR(50),
	DLVR_TYP_ID NUMBER(38,0),
	DLVR_TYP_DS VARCHAR(25)
);


-- Set public, secret keys
SET V_AWS_KEY_ID = 'AKIA5JDY2QSXTDGWSZLO';
SET V_AWS_SECRET_KEY='';

-- ********************************************************************
-- External Stage pointing to S3 
-- ********************************************************************

CREATE OR REPLACE STAGE STAGE_QUICKSERVE_POS
  FILE_FORMAT = csvformat
  URL = 's3://quickserve/' 
  credentials=(AWS_KEY_ID=$V_AWS_KEY_ID AWS_SECRET_KEY=$V_AWS_SECRET_KEY) -- Embed the credentials in the stage
  directory=(enable=true)
  ;

-- ********************************************************************
-- Snowpipe
-- ********************************************************************
-- Create a Snowflake pipe object to load data from the external stage into a Snowflake table
CREATE OR REPLACE PIPE QUICKSERVE_POS_PIPE
AUTO_INGEST = TRUE -- Enable auto-ingest to automatically load new data as it becomes available, will create SQS Queue.
AS
COPY INTO PUBLIC.LND_POS_TRN_LVL_HDR -- Destination table in Snowflake
FROM  @STAGE_QUICKSERVE_POS -- Source external stage
FILE_FORMAT = (FORMAT_NAME = csvformat) -- Specify the file format for parsing the data
ON_ERROR = CONTINUE -- Specify error handling behavior (CONTINUE or ABORT)
;

-- Get our SQS ARN from our stage
SHOW PIPES; -- arn:aws:sqs:us-east-1:381491880937:sf-snowpipe-AIDAVRUVQEPUZQFGKIS5R-VimNtX3IMMmfXaP_bvvXvw
SHOW STAGES;

-- Update Event notifications on our S3 bucket to send notifications to SQS using arn.

-- Add files to bucket and confirm load
SELECT * 
FROM PUBLIC.LND_POS_TRN_LVL_HDR
;
